---
- set_fact: rvm_wrapper_command="cd {{current_path}} && ~/.rvm/bin/rvm ruby-{{ruby_version}}@{{ruby_gemset}} --create do"

- name: start passenger
  shell: "{{ rvm_wrapper_command }} bash -lc 'foreman start -f Procfile.{{rails_env_name}}'"

- name: restart passenger
  shell: "cd {{shared_path}}/tmp && touch restart.txt"
