source 'https://rubygems.org'
ruby '2.4.1'

gem 'byebug'
gem 'sequel'
gem 'sequel-rake'
gem 'passenger', '>= 5.0.25', require: 'phusion_passenger/rack_handler'
gem 'foreman'
gem 'figaro'
gem 'pg', '~> 0.18.4'
gem 'rack'
