# config/database.yml
development:
  adapter: 'postgresql'
  encoding: utf-8
  host: 'localhost'
  username:
  password:
  database:
  max_connections:

production:
  adapter: 'postgresql'
  encoding: utf-8
  host: 'localhost'
  username:
  password:
  database:
  max_connections:

staging:
  adapter: 'postgresql'
  encoding: utf-8
  host: 'localhost'
  username:
  password:
  database:
  max_connections:
