# config/database.yml
first:
  adapter: 'postgresql'
  encoding: utf-8
  host:
  username:
  password:
  database:

second:
  adapter: 'postgresql'
  encoding: utf-8
  host:
  username:
  password:
  database: